### ISSUE TITLE
How could we export various types of contents?

### ISSUE THREAD

**Issue by EmranAhmed** [dtbaker/envato-wp-theme-setup-wizard#1]
How could we export contents or which plugins should we use to export?
- widget_positions.json
- options.json
- variations.xml
- widget_positions.json etc.

**Comment by dtbaker** [comment]
The XML files are generated using the standard Tools > Export feature in WordPress ( details here: https://codex.wordpress.org/Tools_Export_Screen )

The json file content can be generated by adding `&export=true` to the URL of the first wizard page. This shows some content on the screen that can be manually copied and pasted into those json files. 

So basically setup a live public demo (not localhost) as you like it. Install this wizard on that live demo. Export xml content. Export json content. 

Then run the wizard again on a fresh local wordpress install and see if it imports everything correctly.
