### ISSUE TITLE
Unable to save session values

### ISSUE THREAD

**Issue by thewebsitedev** [dtbaker/envato-wp-theme-setup-wizard#11]
Hello,

I have an issue! The session values are empty. I see the session files being generated but the values are empty. I just end up with 'Failed to find WordPress return URL. Please report this error to the item author.'

**Comment by dtbaker** [comment]
Is mod_security running on that hosting account (you may need to contact the hosting provider to find out). See if you can disable it for that particular api directory. Do normal sessions work in other PHP scripts? What is the full url displayed on the page that is showing this error message?

**Comment by thewebsitedev** [comment]
I use WPEngine. The support guy said that they don't use mod security on WPEngine platform. I tried on Digital Ocean server as well but no luck.

**Comment by thewebsitedev** [comment]
Forgot to mention that I get stuck on the loading page. I guess since the form action link is empty.
![screen shot 2016-01-20 at 5 23 16 pm](https://cloud.githubusercontent.com/assets/4481867/12448269/d1ae57f0-bf9a-11e5-9010-cfc7de107fa7.png)

**Comment by thewebsitedev** [comment]
Can't we use cookies rather than sessions?

**Comment by dtbaker** [comment]
Did you ever figure this one out? Sorry I don't have access to a wpengine account to test this on. It shouldn't be too hard to swap the _SESSION code over to plain old _COOKIES
