### ISSUE TITLE
How to export content just like yours

### ISSUE THREAD

**Issue by ghost** [dtbaker/envato-wp-theme-setup-wizard#14]
Hi @dtbaker,
there are some options to export demo content from existing demo site but I wonder how you separately exported for all types like below.

|---
     |--- all.xml
     |--- menu.json
     |--- options.json
     |--- products.xml
     |--- variations.xml
     |--- widget_options.json
     |--- widget_positions.json

**Comment by dtbaker** [comment]
On the first page of the setup wizard try to add `&export=true` to the URL

**Comment by wildrain** [comment]
How can I get widgets_options.json and widgets_positions.json data ? Is there any plugin or tools to export these .json data from an existing site.

**Comment by dtbaker** [comment]
On the first page of the setup wizard try to add `&export=true` to the end of the URL
