### ISSUE TITLE
bbPress conflict

### ISSUE THREAD

**Issue by ghost** [dtbaker/envato-wp-theme-setup-wizard#15]
Hi @dtbaker,
When I preinstalled bbpress I am having the error below.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'filter_permalink' not found or invalid function name in C:\wamp\www\themeforest\wordpress\statix\wp-includes\plugin.php on line 235

Have you ever tried using this wizard in theme while woocommerce and bbpress installed?

Thanks

**Comment by dtbaker** [comment]
Hey try the latest update, lots has changed.
