### ISSUE TITLE
all.xml not working  , function missing

### ISSUE THREAD

**Issue by techsaqib** [dtbaker/envato-wp-theme-setup-wizard#17]
Hi , please provide me the complete function for make working all.xml 

i include the 

```
private function _content_install_pages(){
    return $this->_import_wordpress_xml_file(__DIR__ ."/content/all.xml");
}
```

in  envato_setup.php giving ajax error , 

and one more thing i want to ask about , m i have to include the 

both 

```
include(get_template_directory().'/lib/envato_setup/envato_setup_init.php'); // Functions

include(get_template_directory().'/lib/envato_setup/envato_setup.php');
```

and i have to include the wodpres-importer.php too... 
in funtion.php 

please help

**Comment by dtbaker** [comment]
Hello,

The latest version of the code does not use the xml files. It uses json files. Please update to latest and see how that goes.
