### ISSUE TITLE
Importing Theme Images

### ISSUE THREAD

**Issue by wpinsite** [dtbaker/envato-wp-theme-setup-wizard#18]
Hi dtbaker,

Amazing script you have created. I am just trying to import the standard theme images using the "default.json" file.

I have been playing around with the function `private function _fetch_remote_file( $url, $post ) {` to try and revert it back to the normal WordPress image importer however am having no luck.

Whenever I try and change this function on the wizard under the "Media" section is just hangs and keeps stating "Installing"

Wondering if you have any default code I could use to revert the image import back to the normal WordPress importer.

The script works great apart from being able to import my images.

![capture](https://cloud.githubusercontent.com/assets/6923718/16602806/593f93ee-435a-11e6-89f0-d78b0e81e63a.PNG)

Thanks

**Comment by dtbaker** [comment]
Hey `_fetch_remote_file` will pull in a remote file as long as the URL is a valid URL like http://yourwebsite.com/wp-content/uploads/123.jpg

If the content has "localhost" in the URL or some other local url it will not work, it needs to be a valid hosted image. This is a wordpress security thing. 

What are the URL's for images like in your default.json file?

**Comment by wpinsite** [comment]
Thanks for the response. I am working on my Development machine locally.

I have been trying to import images from a live server to localhost.

An example would be: http://bizstream.wpinsite.com/wp-content/uploads/2015/12/3f48ce8fc2b7e296f69e1ed9562ff5bb-1.gif

**Comment by dtbaker** [comment]
Suggestion, try shorter image file names. Try a short JPEG name something like "test.jpg" and see if that will import.

**Comment by dtbaker** [comment]
Check the latest update, it does local media imports.
