### ISSUE TITLE
Issue with import Pages

### ISSUE THREAD

**Issue by vinnc** [dtbaker/envato-wp-theme-setup-wizard#19]
Hello 

We try to import a pages with  your installer but get an error "Error"

We also noticed that in the class Envato_Theme_Setup_Wizard there is no import function for pages

> _content_install_pages

Also, there is no function to import from xml as you have written in the Readme

> return $this->_import_wordpress_xml_file(__DIR__ ."/content/all.xml");

**Comment by dtbaker** [comment]
_content_install_pages and xml import have been removed and replaced with the better json format (you'll see it's commented out) 

https://github.com/dtbaker/envato-wp-theme-setup-wizard/blob/master/envato_setup/envato_setup.php#L980

_content_install_type handles all the different media types.
