### ISSUE TITLE
Making it work with a plugin

### ISSUE THREAD

**Issue by thewebsitedev** [dtbaker/envato-wp-theme-setup-wizard#2]
I have managed to do most of the stuff and it seems to be working with my plugin. But after I 'Approve' the request for updates I get this error - '_Failed to find WordPress return URL. Please report this error to the item author._'.

What I missed?

**Comment by thewebsitedev** [comment]
I think it was because I was testing locally. How does this handle updates if I have not purchased the theme. Does it output any notice?

**Comment by thewebsitedev** [comment]
Update.

I am getting empty array for `envato_market()->get_options()` [line 880 / envato_setup.php]. I tried to debug but ended up nowhere. Any suggestions?

Is it because I do not own the plugin?

**Comment by thewebsitedev** [comment]
Ha! got it to work finally. It was all because Envato Market plugin was loaded after my plugin so it could not read 'envato_market' function. :|

Now I just need to test it with one of my buyers.

**Comment by dtbaker** [comment]
Great stuff!
