### ISSUE TITLE
Could not load installer

### ISSUE THREAD

**Issue by blicca** [dtbaker/envato-wp-theme-setup-wizard#22]
Thanks for this great installer.

I wish I can use it but no chance. I have upload api folder to my server. ( of course I have changed id, secret and url). 

Then uploaded envato_setup folder 
mytheme / plugins / envato_setup

I have added to function.php 

```
include (get_template_directory() . 'plugins/envato_setup/envato_setup.php');

add_filter('my_theme_theme_setup_wizard_username', 'my_theme_set_theme_setup_wizard_username', 10);
if( ! function_exists('my_theme_set_theme_setup_wizard_username') ){
    function my_theme_set_theme_setup_wizard_username($username){
        return 'myUser';
    }
}

add_filter('my_theme_theme_setup_wizard_oauth_script', 'my_theme_set_theme_setup_wizard_oauth_script', 10);
if( ! function_exists('my_theme_set_theme_setup_wizard_oauth_script') ){
    function my_theme_set_theme_setup_wizard_oauth_script($oauth_url){
        return 'http://mysite.com/envato/api/server-script.php';
    }
}
```

There is not any screen for setup theme. I have checked Appearence and other menus on wordpress. Tried deactivate and reactivate theme. Tried to include other files too **envato_setup_init.php** .... 
I have tried to include files to mytheme/plugins/myUsername/envato_setup... Tried all combination, checked everything but could not open setup screen.

I am going to lose my mind :D What's your suggestion :)

**Comment by blicca** [comment]
First step is done now. Now trying to export

**Comment by dtbaker** [comment]
Glad you got this fixed. Was there something in particular I can improve in the documentation to help others?

**Comment by blicca** [comment]
I am not sure what I did wrong first.

Changing folder url for json (and images) may be explained more. 

"Copy the envato_setup folder into your private $envato_usernameheme folder." It confuses me. 

Copy your files into theme folder whereever you want but change line bla bla bla... Dont forget to include envato_setup.php and envato_setup_ini in functions.php .... 

Thank you so much. It's working great. 
"Ultimate_VC_Addons" gives error but it's working with error :) 

Now I am trying to add multiple import like "choose your demo that you want to install" before starting to default content.

**Comment by dtbaker** [comment]
I have multiple demo code here, I will upload tomorrow.

**Comment by blicca** [comment]
I am working for a few hours "multiple demo" :D Now I stopped it.  I could not pass variable between steps. and could not choose folder etc..

Waiting tomorrow. 

Btw,

> ```
>           public function theme_setup_wizard_steps($steps){
>               unset($steps['design']);
>               unset($steps['customize']);
>               return $steps;
>           }
> ```

Not working for me. envato_setup_logo_image filter is working but steps filter does not work.
One last thing, you may be think adding '_wp_page_template'  to default meta in export.php

**Comment by blicca** [comment]
Is there any news for multiple demo code?

**Comment by dtbaker** [comment]
Yes please have a look at the latest code

**Comment by blicca** [comment]
I will test it as soon as possible. Thank you. You're great.
