### ISSUE TITLE
Request: Register as a composer package

### ISSUE THREAD

**Issue by vburlak** [dtbaker/envato-wp-theme-setup-wizard#3]
Hi, @dtbaker .

Very inspired to see that amazing plugin.
Please, can you register repo as a [composer package](https://packagist.org/)

**Comment by dtbaker** [comment]
It's a little tricky because there's the `api` folder and `envato_setup` folder which both need to be deployed to two different locations. `api` goes to your server. `envato_setup` goes to your theme.

**Comment by dtbaker** [comment]
See how that goes. I setup `package-path` to just include `envato_setup` - not sure if that will work

https://packagist.org/packages/dtbaker/envato-wp-theme-setup-wizard

**Comment by vburlak** [comment]
@dtbaker thanks. 
But it will be more beautiful, together within using repository's tags/releases.

The repository has not yet any release/tag and composer showing alert:

```
Could not find package dtbaker/envato-wp-theme-setup-wizard at any version for your minimum-stability (stable).
```

For any, who want to require package without any available version should update their composer.json in parent project(actually theme's composer.json)

``` json
"repositories": [
     {
          "type": "vcs",
          "url": "https://github.com/dtbaker/envato-wp-theme-setup-wizard"
     }
],
"require": {
     "dtbaker/envato-wp-theme-setup-wizard": "dev-master"
},
```

Hope, it will be helpful for someone.
