### ISSUE TITLE
Can you please add license?

### ISSUE THREAD

**Issue by lumberman** [dtbaker/envato-wp-theme-setup-wizard#4]
Hi there,
Amazing job!

Can you please add license to this project? 
Without it we can't legally use/copy/change/improve it in any way.

Thank you.

**Comment by ahmadawais** [comment]
Same question. Can you add GPL-2.0 license so that we can all use it.

**Comment by dtbaker** [comment]
Sorry guys thought I added it through the github UI but it's not showing.

**Comment by dtbaker** [comment]
There we go 907b4e2967ff39c124380b41b465488c022f1dd0
