### ISSUE TITLE
Theme Configuratiions

### ISSUE THREAD

**Issue by ahmadawais** [dtbaker/envato-wp-theme-setup-wizard#9]
I love this script, but would love to see how you integrated it in your theme. Can you share the theme with me? me @ (myusername).com ? Or let me know when it is available to be downloaded/bought.

**Comment by dtbaker** [comment]
This update script is integrated into this <a href="http://themeforest.net/item/beautiful-watercolor-hand-painted-creative-wordpress/14157442">Beautiful Watercolor</a> WordPress theme that was released a few days ago.

It is pretty much an exact copy of what is here. The `envato_setup` folder from github here is in `wp-content/themes/beautiful-watercolor/plugins/envato_setup/` and in functions.php I just include `plugins/envato_setup/envato_setup.php`. 

However yes there are quite a few things in this script that reference other functions etc.. within the core theme (like getting the list of available theme colors). So copying & pasting the code into another theme wouldn't work straight away.

**Comment by ahmadawais** [comment]
Thanks :)
